---
title: "R Notebook"
output: html_notebook
---
```{r}
library("nnet")
library("e1071")
require(XLConnect)
library("randomForest")
library("dplyr")
library("caret")
library("writexl")
library("neuralnet")
library(caTools)
library("ROCR")
library("DMwR")
library("Boruta")
print("Loaded Packages")
```


```{r}


```

```{r}
print("Loading data")
wb = loadWorkbook("ra.xlsx")
df = readWorksheet(wb, sheet = "Training Dataset", header = TRUE)
print("Data set Loaded...")
#s_df <-  sample(1:nrow(df))
#df <- df[s_df, ]  #manual shuffling code
#head(df)
dim(df)  # checking dimesions

```


```{r}
df1 = df %>% mutate_if(is.character, as.factor) # changing character to as a factor
df1$Treatment <- as.factor(df1$Treatment)
table(df1$Treatment)
#Changing range values to single digit
new_df <- mutate(df1, Age=ifelse(Age =="0-19",0 ,Age),
                 Age=ifelse(Age =="20-29",1,Age),Age=ifelse(Age =="30-39",2 ,Age),
                 Age=ifelse(Age =="40-49",3,Age),Age=ifelse(Age =="50-59",4 ,Age),
                 Age=ifelse(Age =="60-69",5,Age),Age=ifelse(Age =="70-79",6 ,Age),
                 Age=ifelse(Age ==">=80",7,Age))

dim(new_df)

sapply( new_df, function(x) sum(is.na(x))) #to check null value counts in each column

str(new_df)


```


```{r}
getmode <- function(v) {
   v1 <- na.omit(v) # removing NA 
   uniqv <- unique(v1)
   uniqv[which.max(tabulate(match(v1, uniqv)))]
}

for(i in 2:ncol(new_df)){
  
  if(length(unique(new_df[,i]))  == 3){
    fff = getmode(new_df[,i]) # get mode of the column
    new_df[is.na(new_df[,i]), i] <- fff
    
  }else {
    
    new_df[is.na(new_df[,i]), i] <- round(median(new_df[,i], na.rm = TRUE)) # replacing with mean of column
    
  }
}

str(new_df)
sapply( new_df, function(x) sum(is.na(x)))

write_xlsx(new_df,"E:\\stdies\\Data_Science\\q3\\datascience\\project\\Referral_Advice\\new_RA.xlsx")

```


```{r}
#Visualization of data set labels

one_Value = filter(new_df,new_df$Treatment == 1)
two_Value = filter(new_df,new_df$Treatment == 2)
three_Value = filter(new_df,new_df$Treatment == 3)
four_Value = filter(new_df,new_df$Treatment == 4)
five_Value = filter(new_df,new_df$Treatment == 5)

H <- c(length(one_Value$Treatment),length(two_Value$Treatment),length(three_Value$Treatment)
       ,length(four_Value$Treatment),length(five_Value$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",main="LBP Data Volumes",border="red")
pie(table(new_df$Treatment))


```


```{r}
bor <- Boruta(Treatment ~.,data = new_df , doTrace = 2, maxRuns = 500 )
```


```{r}
plot(bor, las =2 , cex.axis = 0.7)
ten <- TentativeRoughFix(bor)
print(ten)
getNonRejectedFormula(bor)
getConfirmedFormula(bor)

```


```{r}
library(caTools)
set.seed(222)
sample = sample.split(new_df,SplitRatio = 0.70)
train1 =subset(new_df,sample ==TRUE)
test1=subset(new_df, sample==FALSE)

# PLOTTING GRAPH FOR TRAINING SET

one_Value_tr = filter(train1,train1$Treatment == 1)
two_Value_tr = filter(train1,train1$Treatment == 2)
three_Value_tr = filter(train1,train1$Treatment == 3)
four_Value_tr = filter(train1,train1$Treatment == 4)
five_Value_tr = filter(train1,train1$Treatment == 5)


length(one_Value_tr$Treatment)
length(two_Value_tr$Treatment)
length(three_Value_tr$Treatment)
length(four_Value_tr$Treatment)
length(five_Value_tr$Treatment)
print("----------------------")
H <- c(length(one_Value_tr$Treatment),length(two_Value_tr$Treatment),length(three_Value_tr$Treatment)
       ,length(four_Value_tr$Treatment),length(five_Value_tr$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",ylim=c(0,1000),main="LBP training Data Volumes",border="red")
pie(table(H))

# PLOTTING GRAPH FOR TEST SET

one_Value_te = filter(test1,test1$Treatment == 1)
two_Value_te = filter(test1,test1$Treatment == 2)
three_Value_te = filter(test1,test1$Treatment == 3)
four_Value_te = filter(test1,test1$Treatment == 4)
five_Value_te = filter(test1,test1$Treatment == 5)

length(one_Value_te$Treatment)
length(two_Value_te$Treatment)
length(three_Value_te$Treatment)
length(four_Value_te$Treatment)
length(five_Value_te$Treatment)

H <- c(length(one_Value_te$Treatment),length(two_Value_te$Treatment),length(three_Value_te$Treatment)
       ,length(four_Value_te$Treatment),length(five_Value_te$Treatment))

M <- c("Advice","Rehab","surgery","inj/med","comb 1-4")

barplot.default(H,names.arg=M,xlab="Labels",ylab="Counts",col="blue",ylim=c(0,1000),main="LBP test Data Volumes",border="red")





```


```{r}
rf <- randomForest(formula = Treatment ~ Fever + Duration_of_pain + Irrational_thoughts_work +   Kinesiophobia_physical_exercise + Age + Uses_analgesics +  Serious_disease + Continuous_pain + Trauma + Paidwork, data = train1 ,importance=TRUE)

#


print(rf)
plot(rf, )

#t <- tuneRF(train1[,-1],train1[,1],stepFactor = 0.5, plot=TRUE, ntreeTry = 300, trace = TRUE,
#           improve = 0.05)


varImpPlot(rf)


```


```{r}
pre_train_mrf = predict(rf, train1, type = "class")

table(pre_train_mrf)
table(train1$Treatment)

u <- union(pre_train_mrf, train1$Treatment)
t <- table(factor(pre_train_mrf, u), factor(train1$Treatment, u))
confusionMatrix(t)


```


```{r}
pre_train_mrf = predict(rf, test1, type = "class")
#print(pre)
#print(test1$Treatment)

table(pre_train_mrf)
table(test1$Treatment)
u <- union(pre_train_mrf, test1$Treatment)
t <- table(factor(pre_train_mrf, u), factor(test1$Treatment, u))
confusionMatrix(t)

```


```{r}
```

